// Code generated by SQLBoiler 4.3.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Blobs            string
	Gcodes           string
	SchemaMigrations string
}{
	Blobs:            "blobs",
	Gcodes:           "gcodes",
	SchemaMigrations: "schema_migrations",
}
