[build]
cmd = "go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "./tmp/main agent --websocket-host localhost --websocket-port 8080 --serial-device /dev/ttyS3"

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Stop running old binary when build errors occur.
stop_on_error = true
