package agent

// GCodeAutoHome is the script for testing and autohoming
const GCodeAutoHome = `M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm/sec
M204 P500 R1000 T500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107 ; disable fan
G90 ; use absolute coordinatsces
M83 ; extruder relative mode
G28 ; home all`

// GCodeLevelBedTest level bed command
const GCodeLevelBedTest = `; generated by PrusaSlicer 2.3.0-alpha1+win64 on 2020-11-25 at 14:17:30 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.38mm
; first layer extrusion width = 0.42mm

M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm/sec
M204 P500 R1000 T500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;M107 ; disable fan
M106 P0 S0 ; disable fan
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S220 ; set extruder temp
M140 S70 ; set bed temp
M190 S70 ; wait for bed temp
M109 S220 ; wait for extruder temp
G28 ; home all
G29 ; auto bed level
G1 Z2 F240
G1 X2 Y10 F3000
G1 Z0.28 F240
G92 E0.0
G1 Y190 E15.0 F1500.0 ; intro line
G1 X2.3 F5000
G1 Y10 E15.0 F1200.0 ; intro line
G92 E0.0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
; LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.2


G1 E-5.00000 F3600.00000 ; retract
G1 Z0.200 F9000.000 ; move to next layer (0)
;AFTER_LAYER_CHANGE
;0.2
G1 X20.808 Y20.830 ; move to first skirt point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Skirt
G1 F1200.000
G1 X21.579 Y20.309 E0.02627 ; skirt
G1 X22.491 Y20.123 E0.02627 ; skirt
G1 X212.504 Y20.123 E5.36194 ; skirt
G1 X213.406 Y20.302 E0.02595 ; skirt
G1 X214.175 Y20.813 E0.02606 ; skirt
G1 X214.691 Y21.579 E0.02606 ; skirt
G1 X214.877 Y22.480 E0.02595 ; skirt
G1 X214.877 Y212.508 E5.36237 ; skirt
G1 X214.698 Y213.406 E0.02585 ; skirt
G1 X214.192 Y214.170 E0.02585 ; skirt
G1 X213.417 Y214.693 E0.02638 ; skirt
G1 X212.500 Y214.877 E0.02641 ; skirt
G1 X22.492 Y214.877 E5.36180 ; skirt
G1 X21.594 Y214.698 E0.02585 ; skirt
G1 X20.830 Y214.192 E0.02585 ; skirt
G1 X20.307 Y213.417 E0.02638 ; skirt
G1 X20.123 Y212.500 E0.02641 ; skirt
G1 X20.123 Y22.492 E5.36180 ; skirt
G1 X20.302 Y21.594 E0.02585 ; skirt
G1 X20.775 Y20.880 E0.02416 ; skirt
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X21.579 Y20.309 E-0.46868 ; wipe and retract
G1 X22.491 Y20.123 E-0.44221 ; wipe and retract
G1 X23.574 Y20.123 E-0.51411 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X192.710 Y192.710 F9000.000 ; move to first perimeter point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:External perimeter
G1 F1200.000
G1 X212.290 Y192.710 E0.55253 ; perimeter
G1 X212.290 Y212.290 E0.55253 ; perimeter
G1 X192.710 Y212.290 E0.55253 ; perimeter
G1 X192.710 Y192.770 E0.55083 ; perimeter
G1 X193.096 Y192.814 F9000.000 ; move inwards before travel
G1 X193.087 Y193.087 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200.000
G1 X211.913 Y193.087 E0.53124 ; perimeter
G1 X211.913 Y211.913 E0.53124 ; perimeter
G1 X193.087 Y211.913 E0.53124 ; perimeter
G1 X193.087 Y193.147 E0.52955 ; perimeter
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X196.087 Y193.138 E-1.42500 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X211.838 Y193.927 F9000.000 ; move to first infill point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Solid infill
G1 F1200.000
G1 X211.243 Y193.332 E0.02379 ; infill
G1 X210.708 Y193.332 E0.01513 ; infill
G1 X211.668 Y194.292 E0.03839 ; infill
G1 X211.668 Y194.826 E0.01513 ; infill
G1 X210.174 Y193.332 E0.05979 ; infill
G1 X209.639 Y193.332 E0.01513 ; infill
G1 X211.668 Y195.361 E0.08118 ; infill
G1 X211.668 Y195.896 E0.01513 ; infill
G1 X209.104 Y193.332 E0.10257 ; infill
G1 X208.570 Y193.332 E0.01513 ; infill
G1 X211.668 Y196.430 E0.12396 ; infill
G1 X211.668 Y196.965 E0.01513 ; infill
G1 X208.035 Y193.332 E0.14535 ; infill
G1 X207.500 Y193.332 E0.01513 ; infill
G1 X211.668 Y197.500 E0.16674 ; infill
G1 X211.668 Y198.034 E0.01513 ; infill
G1 X206.966 Y193.332 E0.18814 ; infill
G1 X206.431 Y193.332 E0.01513 ; infill
G1 X211.668 Y198.569 E0.20953 ; infill
G1 X211.668 Y199.104 E0.01513 ; infill
G1 X205.896 Y193.332 E0.23092 ; infill
G1 X205.362 Y193.332 E0.01513 ; infill
G1 X211.668 Y199.638 E0.25231 ; infill
G1 X211.668 Y200.173 E0.01513 ; infill
G1 X204.827 Y193.332 E0.27370 ; infill
G1 X204.292 Y193.332 E0.01513 ; infill
G1 X211.668 Y200.708 E0.29509 ; infill
G1 X211.668 Y201.242 E0.01513 ; infill
G1 X203.758 Y193.332 E0.31649 ; infill
G1 X203.223 Y193.332 E0.01513 ; infill
G1 X211.668 Y201.777 E0.33788 ; infill
G1 X211.668 Y202.312 E0.01513 ; infill
G1 X202.688 Y193.332 E0.35927 ; infill
G1 X202.154 Y193.332 E0.01513 ; infill
G1 X211.668 Y202.846 E0.38066 ; infill
G1 X211.668 Y203.381 E0.01513 ; infill
G1 X201.619 Y193.332 E0.40205 ; infill
G1 X201.085 Y193.332 E0.01513 ; infill
G1 X211.668 Y203.915 E0.42344 ; infill
G1 X211.668 Y204.450 E0.01513 ; infill
G1 X200.550 Y193.332 E0.44484 ; infill
G1 X200.015 Y193.332 E0.01513 ; infill
G1 X211.668 Y204.985 E0.46623 ; infill
G1 X211.668 Y205.519 E0.01513 ; infill
G1 X199.481 Y193.332 E0.48762 ; infill
G1 X198.946 Y193.332 E0.01513 ; infill
G1 X211.668 Y206.054 E0.50901 ; infill
G1 X211.668 Y206.589 E0.01513 ; infill
G1 X198.411 Y193.332 E0.53040 ; infill
G1 X197.877 Y193.332 E0.01513 ; infill
G1 X211.668 Y207.123 E0.55179 ; infill
G1 X211.668 Y207.658 E0.01513 ; infill
G1 X197.342 Y193.332 E0.57319 ; infill
G1 X196.807 Y193.332 E0.01513 ; infill
G1 X211.668 Y208.193 E0.59458 ; infill
G1 X211.668 Y208.727 E0.01513 ; infill
G1 X196.273 Y193.332 E0.61597 ; infill
G1 X195.738 Y193.332 E0.01513 ; infill
G1 X211.668 Y209.262 E0.63736 ; infill
G1 X211.668 Y209.797 E0.01513 ; infill
G1 X195.203 Y193.332 E0.65875 ; infill
G1 X194.669 Y193.332 E0.01513 ; infill
G1 X211.668 Y210.331 E0.68014 ; infill
G1 X211.668 Y210.866 E0.01513 ; infill
G1 X194.134 Y193.332 E0.70154 ; infill
G1 X193.599 Y193.332 E0.01513 ; infill
G1 X211.668 Y211.401 E0.72293 ; infill
G1 X211.668 Y211.668 E0.00756 ; infill
G1 X211.400 Y211.668 E0.00756 ; infill
G1 X193.332 Y193.600 E0.72293 ; infill
G1 X193.332 Y194.134 E0.01513 ; infill
G1 X210.866 Y211.668 E0.70153 ; infill
G1 X210.331 Y211.668 E0.01513 ; infill
G1 X193.332 Y194.669 E0.68014 ; infill
G1 X193.332 Y195.203 E0.01513 ; infill
G1 X209.797 Y211.668 E0.65875 ; infill
G1 X209.262 Y211.668 E0.01513 ; infill
G1 X193.332 Y195.738 E0.63736 ; infill
G1 X193.332 Y196.273 E0.01513 ; infill
G1 X208.727 Y211.668 E0.61597 ; infill
G1 X208.193 Y211.668 E0.01513 ; infill
G1 X193.332 Y196.807 E0.59458 ; infill
G1 X193.332 Y197.342 E0.01513 ; infill
G1 X207.658 Y211.668 E0.57318 ; infill
G1 X207.123 Y211.668 E0.01513 ; infill
G1 X193.332 Y197.877 E0.55179 ; infill
G1 X193.332 Y198.411 E0.01513 ; infill
G1 X206.589 Y211.668 E0.53040 ; infill
G1 X206.054 Y211.668 E0.01513 ; infill
G1 X193.332 Y198.946 E0.50901 ; infill
G1 X193.332 Y199.481 E0.01513 ; infill
G1 X205.519 Y211.668 E0.48762 ; infill
G1 X204.985 Y211.668 E0.01513 ; infill
G1 X193.332 Y200.015 E0.46623 ; infill
G1 X193.332 Y200.550 E0.01513 ; infill
G1 X204.450 Y211.668 E0.44483 ; infill
G1 X203.915 Y211.668 E0.01513 ; infill
G1 X193.332 Y201.085 E0.42344 ; infill
G1 X193.332 Y201.619 E0.01513 ; infill
G1 X203.381 Y211.668 E0.40205 ; infill
G1 X202.846 Y211.668 E0.01513 ; infill
G1 X193.332 Y202.154 E0.38066 ; infill
G1 X193.332 Y202.689 E0.01513 ; infill
G1 X202.311 Y211.668 E0.35927 ; infill
G1 X201.777 Y211.668 E0.01513 ; infill
G1 X193.332 Y203.223 E0.33788 ; infill
G1 X193.332 Y203.758 E0.01513 ; infill
G1 X201.242 Y211.668 E0.31648 ; infill
G1 X200.708 Y211.668 E0.01513 ; infill
G1 X193.332 Y204.292 E0.29509 ; infill
G1 X193.332 Y204.827 E0.01513 ; infill
G1 X200.173 Y211.668 E0.27370 ; infill
G1 X199.638 Y211.668 E0.01513 ; infill
G1 X193.332 Y205.362 E0.25231 ; infill
G1 X193.332 Y205.896 E0.01513 ; infill
G1 X199.104 Y211.668 E0.23092 ; infill
G1 X198.569 Y211.668 E0.01513 ; infill
G1 X193.332 Y206.431 E0.20953 ; infill
G1 X193.332 Y206.966 E0.01513 ; infill
G1 X198.034 Y211.668 E0.18813 ; infill
G1 X197.500 Y211.668 E0.01513 ; infill
G1 X193.332 Y207.500 E0.16674 ; infill
G1 X193.332 Y208.035 E0.01513 ; infill
G1 X196.965 Y211.668 E0.14535 ; infill
G1 X196.430 Y211.668 E0.01513 ; infill
G1 X193.332 Y208.570 E0.12396 ; infill
G1 X193.332 Y209.104 E0.01513 ; infill
G1 X195.896 Y211.668 E0.10257 ; infill
G1 X195.361 Y211.668 E0.01513 ; infill
G1 X193.332 Y209.639 E0.08118 ; infill
G1 X193.332 Y210.174 E0.01513 ; infill
G1 X194.826 Y211.668 E0.05978 ; infill
G1 X194.292 Y211.668 E0.01513 ; infill
G1 X193.332 Y210.708 E0.03839 ; infill
G1 X193.332 Y211.243 E0.01513 ; infill
G1 X193.927 Y211.838 E0.02379 ; infill
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X193.332 Y211.243 E-0.39942 ; wipe and retract
G1 X193.332 Y210.708 E-0.25396 ; wipe and retract
G1 X194.292 Y211.668 E-0.64458 ; wipe and retract
G1 X194.559 Y211.668 E-0.12704 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X42.290 Y212.290 F9000.000 ; move to first perimeter point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:External perimeter
G1 F1200.000
G1 X22.710 Y212.290 E0.55253 ; perimeter
G1 X22.710 Y192.710 E0.55253 ; perimeter
G1 X42.290 Y192.710 E0.55253 ; perimeter
G1 X42.290 Y212.230 E0.55083 ; perimeter
G1 X41.904 Y212.186 F9000.000 ; move inwards before travel
G1 X41.913 Y211.913 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200.000
G1 X23.087 Y211.913 E0.53124 ; perimeter
G1 X23.087 Y193.087 E0.53124 ; perimeter
G1 X41.913 Y193.087 E0.53124 ; perimeter
G1 X41.913 Y211.853 E0.52955 ; perimeter
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X38.913 Y211.862 E-1.42500 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X23.927 Y211.838 F9000.000 ; move to first infill point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Solid infill
G1 F1200.000
G1 X23.332 Y211.243 E0.02379 ; infill
G1 X23.332 Y210.708 E0.01513 ; infill
G1 X24.292 Y211.668 E0.03839 ; infill
G1 X24.826 Y211.668 E0.01513 ; infill
G1 X23.332 Y210.174 E0.05978 ; infill
G1 X23.332 Y209.639 E0.01513 ; infill
G1 X25.361 Y211.668 E0.08118 ; infill
G1 X25.896 Y211.668 E0.01513 ; infill
G1 X23.332 Y209.104 E0.10257 ; infill
G1 X23.332 Y208.570 E0.01513 ; infill
G1 X26.430 Y211.668 E0.12396 ; infill
G1 X26.965 Y211.668 E0.01513 ; infill
G1 X23.332 Y208.035 E0.14535 ; infill
G1 X23.332 Y207.500 E0.01513 ; infill
G1 X27.500 Y211.668 E0.16674 ; infill
G1 X28.034 Y211.668 E0.01513 ; infill
G1 X23.332 Y206.966 E0.18813 ; infill
G1 X23.332 Y206.431 E0.01513 ; infill
G1 X28.569 Y211.668 E0.20953 ; infill
G1 X29.104 Y211.668 E0.01513 ; infill
G1 X23.332 Y205.896 E0.23092 ; infill
G1 X23.332 Y205.362 E0.01513 ; infill
G1 X29.638 Y211.668 E0.25231 ; infill
G1 X30.173 Y211.668 E0.01513 ; infill
G1 X23.332 Y204.827 E0.27370 ; infill
G1 X23.332 Y204.292 E0.01513 ; infill
G1 X30.708 Y211.668 E0.29509 ; infill
G1 X31.242 Y211.668 E0.01513 ; infill
G1 X23.332 Y203.758 E0.31648 ; infill
G1 X23.332 Y203.223 E0.01513 ; infill
G1 X31.777 Y211.668 E0.33788 ; infill
G1 X32.311 Y211.668 E0.01513 ; infill
G1 X23.332 Y202.689 E0.35927 ; infill
G1 X23.332 Y202.154 E0.01513 ; infill
G1 X32.846 Y211.668 E0.38066 ; infill
G1 X33.381 Y211.668 E0.01513 ; infill
G1 X23.332 Y201.619 E0.40205 ; infill
G1 X23.332 Y201.085 E0.01513 ; infill
G1 X33.915 Y211.668 E0.42344 ; infill
G1 X34.450 Y211.668 E0.01513 ; infill
G1 X23.332 Y200.550 E0.44483 ; infill
G1 X23.332 Y200.015 E0.01513 ; infill
G1 X34.985 Y211.668 E0.46623 ; infill
G1 X35.519 Y211.668 E0.01513 ; infill
G1 X23.332 Y199.481 E0.48762 ; infill
G1 X23.332 Y198.946 E0.01513 ; infill
G1 X36.054 Y211.668 E0.50901 ; infill
G1 X36.589 Y211.668 E0.01513 ; infill
G1 X23.332 Y198.411 E0.53040 ; infill
G1 X23.332 Y197.877 E0.01513 ; infill
G1 X37.123 Y211.668 E0.55179 ; infill
G1 X37.658 Y211.668 E0.01513 ; infill
G1 X23.332 Y197.342 E0.57318 ; infill
G1 X23.332 Y196.807 E0.01513 ; infill
G1 X38.193 Y211.668 E0.59458 ; infill
G1 X38.727 Y211.668 E0.01513 ; infill
G1 X23.332 Y196.273 E0.61597 ; infill
G1 X23.332 Y195.738 E0.01513 ; infill
G1 X39.262 Y211.668 E0.63736 ; infill
G1 X39.797 Y211.668 E0.01513 ; infill
G1 X23.332 Y195.203 E0.65875 ; infill
G1 X23.332 Y194.669 E0.01513 ; infill
G1 X40.331 Y211.668 E0.68014 ; infill
G1 X40.866 Y211.668 E0.01513 ; infill
G1 X23.332 Y194.134 E0.70153 ; infill
G1 X23.332 Y193.600 E0.01513 ; infill
G1 X41.400 Y211.668 E0.72293 ; infill
G1 X41.668 Y211.668 E0.00756 ; infill
G1 X41.668 Y211.401 E0.00756 ; infill
G1 X23.599 Y193.332 E0.72293 ; infill
G1 X24.134 Y193.332 E0.01513 ; infill
G1 X41.668 Y210.866 E0.70154 ; infill
G1 X41.668 Y210.331 E0.01513 ; infill
G1 X24.669 Y193.332 E0.68014 ; infill
G1 X25.203 Y193.332 E0.01513 ; infill
G1 X41.668 Y209.797 E0.65875 ; infill
G1 X41.668 Y209.262 E0.01513 ; infill
G1 X25.738 Y193.332 E0.63736 ; infill
G1 X26.273 Y193.332 E0.01513 ; infill
G1 X41.668 Y208.727 E0.61597 ; infill
G1 X41.668 Y208.193 E0.01513 ; infill
G1 X26.807 Y193.332 E0.59458 ; infill
G1 X27.342 Y193.332 E0.01513 ; infill
G1 X41.668 Y207.658 E0.57319 ; infill
G1 X41.668 Y207.123 E0.01513 ; infill
G1 X27.877 Y193.332 E0.55179 ; infill
G1 X28.411 Y193.332 E0.01513 ; infill
G1 X41.668 Y206.589 E0.53040 ; infill
G1 X41.668 Y206.054 E0.01513 ; infill
G1 X28.946 Y193.332 E0.50901 ; infill
G1 X29.481 Y193.332 E0.01513 ; infill
G1 X41.668 Y205.519 E0.48762 ; infill
G1 X41.668 Y204.985 E0.01513 ; infill
G1 X30.015 Y193.332 E0.46623 ; infill
G1 X30.550 Y193.332 E0.01513 ; infill
G1 X41.668 Y204.450 E0.44484 ; infill
G1 X41.668 Y203.915 E0.01513 ; infill
G1 X31.085 Y193.332 E0.42344 ; infill
G1 X31.619 Y193.332 E0.01513 ; infill
G1 X41.668 Y203.381 E0.40205 ; infill
G1 X41.668 Y202.846 E0.01513 ; infill
G1 X32.154 Y193.332 E0.38066 ; infill
G1 X32.688 Y193.332 E0.01513 ; infill
G1 X41.668 Y202.312 E0.35927 ; infill
G1 X41.668 Y201.777 E0.01513 ; infill
G1 X33.223 Y193.332 E0.33788 ; infill
G1 X33.758 Y193.332 E0.01513 ; infill
G1 X41.668 Y201.242 E0.31649 ; infill
G1 X41.668 Y200.708 E0.01513 ; infill
G1 X34.292 Y193.332 E0.29509 ; infill
G1 X34.827 Y193.332 E0.01513 ; infill
G1 X41.668 Y200.173 E0.27370 ; infill
G1 X41.668 Y199.638 E0.01513 ; infill
G1 X35.362 Y193.332 E0.25231 ; infill
G1 X35.896 Y193.332 E0.01513 ; infill
G1 X41.668 Y199.104 E0.23092 ; infill
G1 X41.668 Y198.569 E0.01513 ; infill
G1 X36.431 Y193.332 E0.20953 ; infill
G1 X36.966 Y193.332 E0.01513 ; infill
G1 X41.668 Y198.034 E0.18814 ; infill
G1 X41.668 Y197.500 E0.01513 ; infill
G1 X37.500 Y193.332 E0.16674 ; infill
G1 X38.035 Y193.332 E0.01513 ; infill
G1 X41.668 Y196.965 E0.14535 ; infill
G1 X41.668 Y196.430 E0.01513 ; infill
G1 X38.570 Y193.332 E0.12396 ; infill
G1 X39.104 Y193.332 E0.01513 ; infill
G1 X41.668 Y195.896 E0.10257 ; infill
G1 X41.668 Y195.361 E0.01513 ; infill
G1 X39.639 Y193.332 E0.08118 ; infill
G1 X40.174 Y193.332 E0.01513 ; infill
G1 X41.668 Y194.826 E0.05979 ; infill
G1 X41.668 Y194.292 E0.01513 ; infill
G1 X40.708 Y193.332 E0.03839 ; infill
G1 X41.243 Y193.332 E0.01513 ; infill
G1 X41.838 Y193.927 E0.02379 ; infill
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X41.243 Y193.332 E-0.39946 ; wipe and retract
G1 X40.708 Y193.332 E-0.25396 ; wipe and retract
G1 X41.668 Y194.292 E-0.64462 ; wipe and retract
G1 X41.668 Y194.559 E-0.12696 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X42.290 Y42.290 F9000.000 ; move to first perimeter point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:External perimeter
G1 F1200.000
G1 X22.710 Y42.290 E0.55253 ; perimeter
G1 X22.710 Y22.710 E0.55253 ; perimeter
G1 X42.290 Y22.710 E0.55253 ; perimeter
G1 X42.290 Y42.230 E0.55083 ; perimeter
G1 X41.904 Y42.186 F9000.000 ; move inwards before travel
G1 X41.913 Y41.913 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200.000
G1 X23.087 Y41.913 E0.53124 ; perimeter
G1 X23.087 Y23.087 E0.53124 ; perimeter
G1 X41.913 Y23.087 E0.53124 ; perimeter
G1 X41.913 Y41.853 E0.52955 ; perimeter
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X38.913 Y41.862 E-1.42500 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X23.927 Y41.838 F9000.000 ; move to first infill point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Solid infill
G1 F1200.000
G1 X23.332 Y41.243 E0.02379 ; infill
G1 X23.332 Y40.708 E0.01513 ; infill
G1 X24.292 Y41.668 E0.03839 ; infill
G1 X24.826 Y41.668 E0.01513 ; infill
G1 X23.332 Y40.174 E0.05978 ; infill
G1 X23.332 Y39.639 E0.01513 ; infill
G1 X25.361 Y41.668 E0.08118 ; infill
G1 X25.896 Y41.668 E0.01513 ; infill
G1 X23.332 Y39.104 E0.10257 ; infill
G1 X23.332 Y38.570 E0.01513 ; infill
G1 X26.430 Y41.668 E0.12396 ; infill
G1 X26.965 Y41.668 E0.01513 ; infill
G1 X23.332 Y38.035 E0.14535 ; infill
G1 X23.332 Y37.500 E0.01513 ; infill
G1 X27.500 Y41.668 E0.16674 ; infill
G1 X28.034 Y41.668 E0.01513 ; infill
G1 X23.332 Y36.966 E0.18813 ; infill
G1 X23.332 Y36.431 E0.01513 ; infill
G1 X28.569 Y41.668 E0.20953 ; infill
G1 X29.104 Y41.668 E0.01513 ; infill
G1 X23.332 Y35.896 E0.23092 ; infill
G1 X23.332 Y35.362 E0.01513 ; infill
G1 X29.638 Y41.668 E0.25231 ; infill
G1 X30.173 Y41.668 E0.01513 ; infill
G1 X23.332 Y34.827 E0.27370 ; infill
G1 X23.332 Y34.292 E0.01513 ; infill
G1 X30.708 Y41.668 E0.29509 ; infill
G1 X31.242 Y41.668 E0.01513 ; infill
G1 X23.332 Y33.758 E0.31648 ; infill
G1 X23.332 Y33.223 E0.01513 ; infill
G1 X31.777 Y41.668 E0.33788 ; infill
G1 X32.311 Y41.668 E0.01513 ; infill
G1 X23.332 Y32.689 E0.35927 ; infill
G1 X23.332 Y32.154 E0.01513 ; infill
G1 X32.846 Y41.668 E0.38066 ; infill
G1 X33.381 Y41.668 E0.01513 ; infill
G1 X23.332 Y31.619 E0.40205 ; infill
G1 X23.332 Y31.085 E0.01513 ; infill
G1 X33.915 Y41.668 E0.42344 ; infill
G1 X34.450 Y41.668 E0.01513 ; infill
G1 X23.332 Y30.550 E0.44483 ; infill
G1 X23.332 Y30.015 E0.01513 ; infill
G1 X34.985 Y41.668 E0.46623 ; infill
G1 X35.519 Y41.668 E0.01513 ; infill
G1 X23.332 Y29.481 E0.48762 ; infill
G1 X23.332 Y28.946 E0.01513 ; infill
G1 X36.054 Y41.668 E0.50901 ; infill
G1 X36.589 Y41.668 E0.01513 ; infill
G1 X23.332 Y28.411 E0.53040 ; infill
G1 X23.332 Y27.877 E0.01513 ; infill
G1 X37.123 Y41.668 E0.55179 ; infill
G1 X37.658 Y41.668 E0.01513 ; infill
G1 X23.332 Y27.342 E0.57318 ; infill
G1 X23.332 Y26.807 E0.01513 ; infill
G1 X38.193 Y41.668 E0.59458 ; infill
G1 X38.727 Y41.668 E0.01513 ; infill
G1 X23.332 Y26.273 E0.61597 ; infill
G1 X23.332 Y25.738 E0.01513 ; infill
G1 X39.262 Y41.668 E0.63736 ; infill
G1 X39.797 Y41.668 E0.01513 ; infill
G1 X23.332 Y25.203 E0.65875 ; infill
G1 X23.332 Y24.669 E0.01513 ; infill
G1 X40.331 Y41.668 E0.68014 ; infill
G1 X40.866 Y41.668 E0.01513 ; infill
G1 X23.332 Y24.134 E0.70153 ; infill
G1 X23.332 Y23.600 E0.01513 ; infill
G1 X41.400 Y41.668 E0.72293 ; infill
G1 X41.668 Y41.668 E0.00756 ; infill
G1 X41.668 Y41.401 E0.00756 ; infill
G1 X23.599 Y23.332 E0.72293 ; infill
G1 X24.134 Y23.332 E0.01513 ; infill
G1 X41.668 Y40.866 E0.70154 ; infill
G1 X41.668 Y40.331 E0.01513 ; infill
G1 X24.669 Y23.332 E0.68014 ; infill
G1 X25.203 Y23.332 E0.01513 ; infill
G1 X41.668 Y39.797 E0.65875 ; infill
G1 X41.668 Y39.262 E0.01513 ; infill
G1 X25.738 Y23.332 E0.63736 ; infill
G1 X26.273 Y23.332 E0.01513 ; infill
G1 X41.668 Y38.727 E0.61597 ; infill
G1 X41.668 Y38.193 E0.01513 ; infill
G1 X26.807 Y23.332 E0.59458 ; infill
G1 X27.342 Y23.332 E0.01513 ; infill
G1 X41.668 Y37.658 E0.57319 ; infill
G1 X41.668 Y37.123 E0.01513 ; infill
G1 X27.877 Y23.332 E0.55179 ; infill
G1 X28.411 Y23.332 E0.01513 ; infill
G1 X41.668 Y36.589 E0.53040 ; infill
G1 X41.668 Y36.054 E0.01513 ; infill
G1 X28.946 Y23.332 E0.50901 ; infill
G1 X29.481 Y23.332 E0.01513 ; infill
G1 X41.668 Y35.519 E0.48762 ; infill
G1 X41.668 Y34.985 E0.01513 ; infill
G1 X30.015 Y23.332 E0.46623 ; infill
G1 X30.550 Y23.332 E0.01513 ; infill
G1 X41.668 Y34.450 E0.44484 ; infill
G1 X41.668 Y33.915 E0.01513 ; infill
G1 X31.085 Y23.332 E0.42344 ; infill
G1 X31.619 Y23.332 E0.01513 ; infill
G1 X41.668 Y33.381 E0.40205 ; infill
G1 X41.668 Y32.846 E0.01513 ; infill
G1 X32.154 Y23.332 E0.38066 ; infill
G1 X32.688 Y23.332 E0.01513 ; infill
G1 X41.668 Y32.312 E0.35927 ; infill
G1 X41.668 Y31.777 E0.01513 ; infill
G1 X33.223 Y23.332 E0.33788 ; infill
G1 X33.758 Y23.332 E0.01513 ; infill
G1 X41.668 Y31.242 E0.31649 ; infill
G1 X41.668 Y30.708 E0.01513 ; infill
G1 X34.292 Y23.332 E0.29509 ; infill
G1 X34.827 Y23.332 E0.01513 ; infill
G1 X41.668 Y30.173 E0.27370 ; infill
G1 X41.668 Y29.638 E0.01513 ; infill
G1 X35.362 Y23.332 E0.25231 ; infill
G1 X35.896 Y23.332 E0.01513 ; infill
G1 X41.668 Y29.104 E0.23092 ; infill
G1 X41.668 Y28.569 E0.01513 ; infill
G1 X36.431 Y23.332 E0.20953 ; infill
G1 X36.966 Y23.332 E0.01513 ; infill
G1 X41.668 Y28.034 E0.18814 ; infill
G1 X41.668 Y27.500 E0.01513 ; infill
G1 X37.500 Y23.332 E0.16674 ; infill
G1 X38.035 Y23.332 E0.01513 ; infill
G1 X41.668 Y26.965 E0.14535 ; infill
G1 X41.668 Y26.430 E0.01513 ; infill
G1 X38.570 Y23.332 E0.12396 ; infill
G1 X39.104 Y23.332 E0.01513 ; infill
G1 X41.668 Y25.896 E0.10257 ; infill
G1 X41.668 Y25.361 E0.01513 ; infill
G1 X39.639 Y23.332 E0.08118 ; infill
G1 X40.174 Y23.332 E0.01513 ; infill
G1 X41.668 Y24.826 E0.05979 ; infill
G1 X41.668 Y24.292 E0.01513 ; infill
G1 X40.708 Y23.332 E0.03839 ; infill
G1 X41.243 Y23.332 E0.01513 ; infill
G1 X41.838 Y23.927 E0.02379 ; infill
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X41.243 Y23.332 E-0.39946 ; wipe and retract
G1 X40.708 Y23.332 E-0.25396 ; wipe and retract
G1 X41.668 Y24.292 E-0.64462 ; wipe and retract
G1 X41.668 Y24.559 E-0.12696 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X107.710 Y107.710 F9000.000 ; move to first perimeter point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:External perimeter
G1 F1200.000
G1 X127.290 Y107.710 E0.55253 ; perimeter
G1 X127.290 Y127.290 E0.55253 ; perimeter
G1 X107.710 Y127.290 E0.55253 ; perimeter
G1 X107.710 Y107.770 E0.55083 ; perimeter
G1 X108.096 Y107.814 F9000.000 ; move inwards before travel
G1 X108.087 Y108.087 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200.000
G1 X126.913 Y108.087 E0.53124 ; perimeter
G1 X126.913 Y126.913 E0.53124 ; perimeter
G1 X108.087 Y126.913 E0.53124 ; perimeter
G1 X108.087 Y108.147 E0.52955 ; perimeter
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X111.087 Y108.138 E-1.42500 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X126.838 Y108.927 F9000.000 ; move to first infill point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Solid infill
G1 F1200.000
G1 X126.243 Y108.332 E0.02379 ; infill
G1 X125.708 Y108.332 E0.01513 ; infill
G1 X126.668 Y109.292 E0.03839 ; infill
G1 X126.668 Y109.826 E0.01513 ; infill
G1 X125.174 Y108.332 E0.05979 ; infill
G1 X124.639 Y108.332 E0.01513 ; infill
G1 X126.668 Y110.361 E0.08118 ; infill
G1 X126.668 Y110.896 E0.01513 ; infill
G1 X124.104 Y108.332 E0.10257 ; infill
G1 X123.570 Y108.332 E0.01513 ; infill
G1 X126.668 Y111.430 E0.12396 ; infill
G1 X126.668 Y111.965 E0.01513 ; infill
G1 X123.035 Y108.332 E0.14535 ; infill
G1 X122.500 Y108.332 E0.01513 ; infill
G1 X126.668 Y112.500 E0.16674 ; infill
G1 X126.668 Y113.034 E0.01513 ; infill
G1 X121.966 Y108.332 E0.18814 ; infill
G1 X121.431 Y108.332 E0.01513 ; infill
G1 X126.668 Y113.569 E0.20953 ; infill
G1 X126.668 Y114.104 E0.01513 ; infill
G1 X120.896 Y108.332 E0.23092 ; infill
G1 X120.362 Y108.332 E0.01513 ; infill
G1 X126.668 Y114.638 E0.25231 ; infill
G1 X126.668 Y115.173 E0.01513 ; infill
G1 X119.827 Y108.332 E0.27370 ; infill
G1 X119.292 Y108.332 E0.01513 ; infill
G1 X126.668 Y115.708 E0.29509 ; infill
G1 X126.668 Y116.242 E0.01513 ; infill
G1 X118.758 Y108.332 E0.31649 ; infill
G1 X118.223 Y108.332 E0.01513 ; infill
G1 X126.668 Y116.777 E0.33788 ; infill
G1 X126.668 Y117.312 E0.01513 ; infill
G1 X117.688 Y108.332 E0.35927 ; infill
G1 X117.154 Y108.332 E0.01513 ; infill
G1 X126.668 Y117.846 E0.38066 ; infill
G1 X126.668 Y118.381 E0.01513 ; infill
G1 X116.619 Y108.332 E0.40205 ; infill
G1 X116.085 Y108.332 E0.01513 ; infill
G1 X126.668 Y118.915 E0.42344 ; infill
G1 X126.668 Y119.450 E0.01513 ; infill
G1 X115.550 Y108.332 E0.44484 ; infill
G1 X115.015 Y108.332 E0.01513 ; infill
G1 X126.668 Y119.985 E0.46623 ; infill
G1 X126.668 Y120.519 E0.01513 ; infill
G1 X114.481 Y108.332 E0.48762 ; infill
G1 X113.946 Y108.332 E0.01513 ; infill
G1 X126.668 Y121.054 E0.50901 ; infill
G1 X126.668 Y121.589 E0.01513 ; infill
G1 X113.411 Y108.332 E0.53040 ; infill
G1 X112.877 Y108.332 E0.01513 ; infill
G1 X126.668 Y122.123 E0.55179 ; infill
G1 X126.668 Y122.658 E0.01513 ; infill
G1 X112.342 Y108.332 E0.57319 ; infill
G1 X111.807 Y108.332 E0.01513 ; infill
G1 X126.668 Y123.193 E0.59458 ; infill
G1 X126.668 Y123.727 E0.01513 ; infill
G1 X111.273 Y108.332 E0.61597 ; infill
G1 X110.738 Y108.332 E0.01513 ; infill
G1 X126.668 Y124.262 E0.63736 ; infill
G1 X126.668 Y124.797 E0.01513 ; infill
G1 X110.203 Y108.332 E0.65875 ; infill
G1 X109.669 Y108.332 E0.01513 ; infill
G1 X126.668 Y125.331 E0.68014 ; infill
G1 X126.668 Y125.866 E0.01513 ; infill
G1 X109.134 Y108.332 E0.70154 ; infill
G1 X108.599 Y108.332 E0.01513 ; infill
G1 X126.668 Y126.401 E0.72293 ; infill
G1 X126.668 Y126.668 E0.00756 ; infill
G1 X126.400 Y126.668 E0.00756 ; infill
G1 X108.332 Y108.600 E0.72293 ; infill
G1 X108.332 Y109.134 E0.01513 ; infill
G1 X125.866 Y126.668 E0.70153 ; infill
G1 X125.331 Y126.668 E0.01513 ; infill
G1 X108.332 Y109.669 E0.68014 ; infill
G1 X108.332 Y110.203 E0.01513 ; infill
G1 X124.797 Y126.668 E0.65875 ; infill
G1 X124.262 Y126.668 E0.01513 ; infill
G1 X108.332 Y110.738 E0.63736 ; infill
G1 X108.332 Y111.273 E0.01513 ; infill
G1 X123.727 Y126.668 E0.61597 ; infill
G1 X123.193 Y126.668 E0.01513 ; infill
G1 X108.332 Y111.807 E0.59458 ; infill
G1 X108.332 Y112.342 E0.01513 ; infill
G1 X122.658 Y126.668 E0.57318 ; infill
G1 X122.123 Y126.668 E0.01513 ; infill
G1 X108.332 Y112.877 E0.55179 ; infill
G1 X108.332 Y113.411 E0.01513 ; infill
G1 X121.589 Y126.668 E0.53040 ; infill
G1 X121.054 Y126.668 E0.01513 ; infill
G1 X108.332 Y113.946 E0.50901 ; infill
G1 X108.332 Y114.481 E0.01513 ; infill
G1 X120.519 Y126.668 E0.48762 ; infill
G1 X119.985 Y126.668 E0.01513 ; infill
G1 X108.332 Y115.015 E0.46623 ; infill
G1 X108.332 Y115.550 E0.01513 ; infill
G1 X119.450 Y126.668 E0.44483 ; infill
G1 X118.915 Y126.668 E0.01513 ; infill
G1 X108.332 Y116.085 E0.42344 ; infill
G1 X108.332 Y116.619 E0.01513 ; infill
G1 X118.381 Y126.668 E0.40205 ; infill
G1 X117.846 Y126.668 E0.01513 ; infill
G1 X108.332 Y117.154 E0.38066 ; infill
G1 X108.332 Y117.689 E0.01513 ; infill
G1 X117.311 Y126.668 E0.35927 ; infill
G1 X116.777 Y126.668 E0.01513 ; infill
G1 X108.332 Y118.223 E0.33788 ; infill
G1 X108.332 Y118.758 E0.01513 ; infill
G1 X116.242 Y126.668 E0.31648 ; infill
G1 X115.708 Y126.668 E0.01513 ; infill
G1 X108.332 Y119.292 E0.29509 ; infill
G1 X108.332 Y119.827 E0.01513 ; infill
G1 X115.173 Y126.668 E0.27370 ; infill
G1 X114.638 Y126.668 E0.01513 ; infill
G1 X108.332 Y120.362 E0.25231 ; infill
G1 X108.332 Y120.896 E0.01513 ; infill
G1 X114.104 Y126.668 E0.23092 ; infill
G1 X113.569 Y126.668 E0.01513 ; infill
G1 X108.332 Y121.431 E0.20953 ; infill
G1 X108.332 Y121.966 E0.01513 ; infill
G1 X113.034 Y126.668 E0.18813 ; infill
G1 X112.500 Y126.668 E0.01513 ; infill
G1 X108.332 Y122.500 E0.16674 ; infill
G1 X108.332 Y123.035 E0.01513 ; infill
G1 X111.965 Y126.668 E0.14535 ; infill
G1 X111.430 Y126.668 E0.01513 ; infill
G1 X108.332 Y123.570 E0.12396 ; infill
G1 X108.332 Y124.104 E0.01513 ; infill
G1 X110.896 Y126.668 E0.10257 ; infill
G1 X110.361 Y126.668 E0.01513 ; infill
G1 X108.332 Y124.639 E0.08118 ; infill
G1 X108.332 Y125.174 E0.01513 ; infill
G1 X109.826 Y126.668 E0.05978 ; infill
G1 X109.292 Y126.668 E0.01513 ; infill
G1 X108.332 Y125.708 E0.03839 ; infill
G1 X108.332 Y126.243 E0.01513 ; infill
G1 X108.927 Y126.838 E0.02379 ; infill
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X108.332 Y126.243 E-0.39942 ; wipe and retract
G1 X108.332 Y125.708 E-0.25396 ; wipe and retract
G1 X109.292 Y126.668 E-0.64458 ; wipe and retract
G1 X109.559 Y126.668 E-0.12704 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X192.710 Y42.290 F9000.000 ; move to first perimeter point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:External perimeter
G1 F1200.000
G1 X192.710 Y22.710 E0.55253 ; perimeter
G1 X212.290 Y22.710 E0.55253 ; perimeter
G1 X212.290 Y42.290 E0.55253 ; perimeter
G1 X192.770 Y42.290 E0.55083 ; perimeter
G1 X192.814 Y41.904 F9000.000 ; move inwards before travel
G1 X193.087 Y41.913 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200.000
G1 X193.087 Y23.087 E0.53124 ; perimeter
G1 X211.913 Y23.087 E0.53124 ; perimeter
G1 X211.913 Y41.913 E0.53124 ; perimeter
G1 X193.147 Y41.913 E0.52955 ; perimeter
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000
G1 X193.138 Y38.913 E-1.42500 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
G1 X211.838 Y23.927 F9000.000 ; move to first infill point
G1 E5.00000 F2400.00000 ; unretract
;TYPE:Solid infill
G1 F1200.000
G1 X211.243 Y23.332 E0.02379 ; infill
G1 X210.708 Y23.332 E0.01513 ; infill
G1 X211.668 Y24.292 E0.03839 ; infill
G1 X211.668 Y24.826 E0.01513 ; infill
G1 X210.174 Y23.332 E0.05979 ; infill
G1 X209.639 Y23.332 E0.01513 ; infill
G1 X211.668 Y25.361 E0.08118 ; infill
G1 X211.668 Y25.896 E0.01513 ; infill
G1 X209.104 Y23.332 E0.10257 ; infill
G1 X208.570 Y23.332 E0.01513 ; infill
G1 X211.668 Y26.430 E0.12396 ; infill
G1 X211.668 Y26.965 E0.01513 ; infill
G1 X208.035 Y23.332 E0.14535 ; infill
G1 X207.500 Y23.332 E0.01513 ; infill
G1 X211.668 Y27.500 E0.16674 ; infill
G1 X211.668 Y28.034 E0.01513 ; infill
G1 X206.966 Y23.332 E0.18814 ; infill
G1 X206.431 Y23.332 E0.01513 ; infill
G1 X211.668 Y28.569 E0.20953 ; infill
G1 X211.668 Y29.104 E0.01513 ; infill
G1 X205.896 Y23.332 E0.23092 ; infill
G1 X205.362 Y23.332 E0.01513 ; infill
G1 X211.668 Y29.638 E0.25231 ; infill
G1 X211.668 Y30.173 E0.01513 ; infill
G1 X204.827 Y23.332 E0.27370 ; infill
G1 X204.292 Y23.332 E0.01513 ; infill
G1 X211.668 Y30.708 E0.29509 ; infill
G1 X211.668 Y31.242 E0.01513 ; infill
G1 X203.758 Y23.332 E0.31649 ; infill
G1 X203.223 Y23.332 E0.01513 ; infill
G1 X211.668 Y31.777 E0.33788 ; infill
G1 X211.668 Y32.312 E0.01513 ; infill
G1 X202.688 Y23.332 E0.35927 ; infill
G1 X202.154 Y23.332 E0.01513 ; infill
G1 X211.668 Y32.846 E0.38066 ; infill
G1 X211.668 Y33.381 E0.01513 ; infill
G1 X201.619 Y23.332 E0.40205 ; infill
G1 X201.085 Y23.332 E0.01513 ; infill
G1 X211.668 Y33.915 E0.42344 ; infill
G1 X211.668 Y34.450 E0.01513 ; infill
G1 X200.550 Y23.332 E0.44484 ; infill
G1 X200.015 Y23.332 E0.01513 ; infill
G1 X211.668 Y34.985 E0.46623 ; infill
G1 X211.668 Y35.519 E0.01513 ; infill
G1 X199.481 Y23.332 E0.48762 ; infill
G1 X198.946 Y23.332 E0.01513 ; infill
G1 X211.668 Y36.054 E0.50901 ; infill
G1 X211.668 Y36.589 E0.01513 ; infill
G1 X198.411 Y23.332 E0.53040 ; infill
G1 X197.877 Y23.332 E0.01513 ; infill
G1 X211.668 Y37.123 E0.55179 ; infill
G1 X211.668 Y37.658 E0.01513 ; infill
G1 X197.342 Y23.332 E0.57319 ; infill
G1 X196.807 Y23.332 E0.01513 ; infill
G1 X211.668 Y38.193 E0.59458 ; infill
G1 X211.668 Y38.727 E0.01513 ; infill
G1 X196.273 Y23.332 E0.61597 ; infill
G1 X195.738 Y23.332 E0.01513 ; infill
G1 X211.668 Y39.262 E0.63736 ; infill
G1 X211.668 Y39.797 E0.01513 ; infill
G1 X195.203 Y23.332 E0.65875 ; infill
G1 X194.669 Y23.332 E0.01513 ; infill
G1 X211.668 Y40.331 E0.68014 ; infill
G1 X211.668 Y40.866 E0.01513 ; infill
G1 X194.134 Y23.332 E0.70154 ; infill
G1 X193.599 Y23.332 E0.01513 ; infill
G1 X211.668 Y41.401 E0.72293 ; infill
G1 X211.668 Y41.668 E0.00756 ; infill
G1 X211.400 Y41.668 E0.00756 ; infill
G1 X193.332 Y23.600 E0.72293 ; infill
G1 X193.332 Y24.134 E0.01513 ; infill
G1 X210.866 Y41.668 E0.70153 ; infill
G1 X210.331 Y41.668 E0.01513 ; infill
G1 X193.332 Y24.669 E0.68014 ; infill
G1 X193.332 Y25.203 E0.01513 ; infill
G1 X209.797 Y41.668 E0.65875 ; infill
G1 X209.262 Y41.668 E0.01513 ; infill
G1 X193.332 Y25.738 E0.63736 ; infill
G1 X193.332 Y26.273 E0.01513 ; infill
G1 X208.727 Y41.668 E0.61597 ; infill
G1 X208.193 Y41.668 E0.01513 ; infill
G1 X193.332 Y26.807 E0.59458 ; infill
G1 X193.332 Y27.342 E0.01513 ; infill
G1 X207.658 Y41.668 E0.57318 ; infill
G1 X207.123 Y41.668 E0.01513 ; infill
G1 X193.332 Y27.877 E0.55179 ; infill
G1 X193.332 Y28.411 E0.01513 ; infill
G1 X206.589 Y41.668 E0.53040 ; infill
G1 X206.054 Y41.668 E0.01513 ; infill
G1 X193.332 Y28.946 E0.50901 ; infill
G1 X193.332 Y29.481 E0.01513 ; infill
G1 X205.519 Y41.668 E0.48762 ; infill
G1 X204.985 Y41.668 E0.01513 ; infill
G1 X193.332 Y30.015 E0.46623 ; infill
G1 X193.332 Y30.550 E0.01513 ; infill
G1 X204.450 Y41.668 E0.44483 ; infill
G1 X203.915 Y41.668 E0.01513 ; infill
G1 X193.332 Y31.085 E0.42344 ; infill
G1 X193.332 Y31.619 E0.01513 ; infill
G1 X203.381 Y41.668 E0.40205 ; infill
G1 X202.846 Y41.668 E0.01513 ; infill
G1 X193.332 Y32.154 E0.38066 ; infill
G1 X193.332 Y32.689 E0.01513 ; infill
G1 X202.311 Y41.668 E0.35927 ; infill
G1 X201.777 Y41.668 E0.01513 ; infill
G1 X193.332 Y33.223 E0.33788 ; infill
G1 X193.332 Y33.758 E0.01513 ; infill
G1 X201.242 Y41.668 E0.31648 ; infill
G1 X200.708 Y41.668 E0.01513 ; infill
G1 X193.332 Y34.292 E0.29509 ; infill
G1 X193.332 Y34.827 E0.01513 ; infill
G1 X200.173 Y41.668 E0.27370 ; infill
G1 X199.638 Y41.668 E0.01513 ; infill
G1 X193.332 Y35.362 E0.25231 ; infill
G1 X193.332 Y35.896 E0.01513 ; infill
G1 X199.104 Y41.668 E0.23092 ; infill
G1 X198.569 Y41.668 E0.01513 ; infill
G1 X193.332 Y36.431 E0.20953 ; infill
G1 X193.332 Y36.966 E0.01513 ; infill
G1 X198.034 Y41.668 E0.18813 ; infill
G1 X197.500 Y41.668 E0.01513 ; infill
G1 X193.332 Y37.500 E0.16674 ; infill
G1 X193.332 Y38.035 E0.01513 ; infill
G1 X196.965 Y41.668 E0.14535 ; infill
G1 X196.430 Y41.668 E0.01513 ; infill
G1 X193.332 Y38.570 E0.12396 ; infill
G1 X193.332 Y39.104 E0.01513 ; infill
G1 X195.896 Y41.668 E0.10257 ; infill
G1 X195.361 Y41.668 E0.01513 ; infill
G1 X193.332 Y39.639 E0.08118 ; infill
G1 X193.332 Y40.174 E0.01513 ; infill
G1 X194.826 Y41.668 E0.05978 ; infill
G1 X194.292 Y41.668 E0.01513 ; infill
G1 X193.332 Y40.708 E0.03839 ; infill
G1 X193.332 Y41.243 E0.01513 ; infill
G1 X193.927 Y41.838 E0.02379 ; infill
G1 E-3.50000 F3600.00000 ; retract
G1 F7200.000;_WIPE
G1 X193.332 Y41.243 E-0.39942 ; wipe and retract
G1 F7200.000;_WIPE
G1 X193.332 Y40.708 E-0.25396 ; wipe and retract
G1 F7200.000;_WIPE
G1 X194.292 Y41.668 E-0.64458 ; wipe and retract
G1 F7200.000;_WIPE
G1 X194.559 Y41.668 E-0.12704 ; wipe and retract
G1 E-0.07500 F3600.00000 ; retract
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z10.2 F600 ; Move print head up
G1 X0 Y200 F3000 ; present print
M84 ; disable motors
;M84 X Y E ; disable motors removed for go app
; filament used [mm] = 174.4
; filament used [cm3] = 0.4
; filament used [g] = 0.5
; filament cost = 0.0
; total filament used [g] = 0.5
; total filament cost = 0.0
; _GP_ESTIMATED_PRINTING_TIME_PLACEHOLDER

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,235x0,235x235,0x235
; bed_temperature = 70
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/ENDER.*/ and nozzle_diameter[0]==0.4";printer_notes=~/.*PRINTER_VENDOR_CREALITY.*/
; complete_objects = 0
; cooling = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Creality PLA @ENDER3"
; default_print_profile = 0.15mm OPTIMAL @ENDER3
; deretract_speed = 40
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+10, max_print_height)} F600{endif} ; Move print head up\nG1 X0 Y200 F3000 ; present print\nM84 ; disable motors\n;M84 X Y E ; disable motors removed for go app
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.9
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 20
; filament_colour = #FFFFFF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25
; filament_density = 1.27
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 8
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "https://all3dp.com/2/petg-print-settings-how-to-find-the-best-settings-for-petg/\n\nhttps://forum.simplify3d.com/viewtopic.php?t=5002"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PETG - PrusaSlicer Suggestions"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 0
; first_layer_bed_temperature = 70
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 220
; gap_fill_speed = 30
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 35%
; infill_speed = 50
; inherits_cummulative = "0.20mm NORMAL @ENDER3";"Generic PETG @ENDER3";"Creality Ender-3"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = topmost
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 50
; max_layer_height = 0.25
; max_print_height = 250
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 20
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 40
; perimeters = 2
; post_process = 
; print_settings_id = 0.20mm NORMAL @ENDER3 - Copy
; printer_model = ENDER3
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3\nPRINTER_HAS_BOWDEN
; printer_settings_id = Creality Ender-3 - Copy
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 40
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 ; home all\nG29 ; auto bed level\nG1 Z2 F240\nG1 X2 Y10 F3000\nG1 Z0.28 F240\nG92 E0.0\nG1 Y190 E15.0 F1500.0 ; intro line\nG1 X2.3 F5000\nG1 Y10 E15.0 F1200.0 ; intro line\nG92 E0.0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 2.5
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 220
; template_custom_gcode = 
; thin_walls = 0
; threads = 4
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 30
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_speed = 150
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
`
